#
# Copyright (c) 2020 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0
#
# SPDX-License-Identifier: EPL-2.0
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-router
spec:
  replicas: 1
  selector:
    matchLabels:
      name: edge-router
  template:
    metadata:
      labels:
        name: edge-router
    spec:
      containers:
      - image: quay.io/interconnectedcloud/qdrouterd:1.10.0
        imagePullPolicy: IfNotPresent
        name: apache-qpid-dispatch-router
        command:
        - /sbin/qdrouterd
        - -c
        - /etc/hono/edge-node-config.json
        env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
        - name: amqps
          containerPort: 5671
          protocol: TCP
        - name: amqp
          containerPort: 5672
          protocol: TCP
        - name: internal
          containerPort: 5673
          protocol: TCP
        - name: health
          containerPort: 8088
          protocol: TCP
        livenessProbe:
          initialDelaySeconds: 180
          periodSeconds: 9
          httpGet:
            path: /healthz
            port: health
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 5
          httpGet:
            path: /healthz
            port: health
        securityContext:
          privileged: false
        volumeMounts:
        - mountPath: /etc/hono
          name: edge-config
          readOnly: true
      volumes:
      - name: edge-config
        secret:
          secretName: edge-config
