#
# Copyright (c) 2019, 2020 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0
#
# SPDX-License-Identifier: EPL-2.0
#
{{- define "hono.qdrouterd-with-artemis.json" -}}
[
  ["router", {
    "id": "Hono.Example.Router",
    "mode": "interior",
    "workerThreads": 3
  }],

  ["authServicePlugin", {
    "name": "Hono Auth",
    "host": "{{ .Release.Name }}-service-auth",
    "port": 5671,
    "sslProfile": "internal"
  }],

  ["sslProfile", {
    "name": "external",
    "protocols": "TLSv1.2",
    "caCertFile": "/etc/hono/trusted-certs.pem",
    "certFile": "/etc/hono/qdrouter-cert.pem",
    "privateKeyFile": "/etc/hono/qdrouter-key.pem"
  }],

  ["sslProfile", {
    "name": "internal",
    "protocols": "TLSv1.2",
    "caCertFile": "/etc/hono/trusted-certs.pem"
  }],

  ["listener", {
    "sslProfile": "external",
    "requireSsl": true,
    "host": "0.0.0.0",
    "port": 5000,
    "maxSessionFrames": 200,
    "linkCapacity": 100,
    "authenticatePeer": true,
    "saslMechanisms": "PLAIN",
    "saslPlugin": "Hono Auth",
    "role": "edge"
  }],

  ["listener", {
    "sslProfile": "external",
    "requireSsl": true,
    "host": "0.0.0.0",
    "port": 5671,
    "maxSessionFrames": 200,
    "linkCapacity": 100,
    "authenticatePeer": true,
    "saslMechanisms": "PLAIN",
    "saslPlugin": "Hono Auth"
  }],

  ["listener", {
    "host": "0.0.0.0",
    "port": 5672,
    "maxSessionFrames": 200,
    "linkCapacity": 100,
    "authenticatePeer": true,
    "saslMechanisms": "PLAIN",
    "saslPlugin": "Hono Auth"
  }],

  ["listener", {
    "host": "0.0.0.0",
    "port": 8088,
    "http": true
  }],

  ["connector", {
    "sslProfile": "internal",
    "name": "artemis",
    "port": 5671,
    "role": "route-container",
    "host": "{{ .Release.Name }}-artemis",
    "saslUsername": "artemis",
    "saslPassword": "artemis",
    "verifyHostname": false
  }],

  ["connector", {
    "sslProfile": "internal",
    "name": "registry",
    "port": 5671,
    "role": "route-container",
    "host": "{{ .Release.Name }}-service-device-registry",
    "saslUsername": "amqp-adapter@HONO",
    "saslPassword": "amqp-secret",
    "verifyHostname": false
  }],

  ["linkRoute", {
    "prefix": "tenant/",
    "direction": "in",
    "connection": "registry"
  }],

  ["linkRoute", {
    "prefix": "tenant/",
    "direction": "out",
    "connection": "registry"
  }],

  ["linkRoute", {
    "prefix": "registration/",
    "direction": "in",
    "connection": "registry"
  }],

  ["linkRoute", {
    "prefix": "registration/",
    "direction": "out",
    "connection": "registry"
  }],

  ["linkRoute", {
    "prefix": "credentials/",
    "direction": "in",
    "connection": "registry"
  }],

  ["linkRoute", {
    "prefix": "credentials/",
    "direction": "out",
    "connection": "registry"
  }],

  ["linkRoute", {
    "prefix": "event/",
    "direction": "in",
    "connection": "artemis"
  }],

  ["linkRoute", {
    "prefix": "event/",
    "direction": "out",
    "connection": "artemis"
  }],

  ["address", {
    "prefix": "telemetry/",
    "distribution": "balanced"
  }],

  ["address", {
    "prefix": "event/",
    "distribution": "balanced"
  }],

  ["policy", {
    "maxConnections": 1000,
    "enableVhostPolicy": true,
    "defaultVhost": "hono"
  }],

  ["vhost", {
      "hostname": "hono",
      "maxConnections": 500,
      "maxConnectionsPerUser": 20,
      "maxConnectionsPerHost": 10,
      "allowUnknownUser": true,
      "groups": {
        "$default": {
          "remoteHosts": "*",
          "maxSessions": 10
        }
      }
  }],

  ["vhost", {
      "hostname": "io-fog",
      "maxConnections": 50,
      "allowUnknownUser": true,
      "groups": {
        "$default": {
          "remoteHosts": "*",
          "maxSessions": 4,
          "maxMessageSize": 131072,
          "allowUserIdProxy": true,
          "allowAnonymousSender": true
        }
      }
  }],

  ["log", {
    "module": "DEFAULT",
    "enable": "info+"
  }]
]
{{- end }}
